In [1]:
import tensorflow as tf
from tensorflow import keras 
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  bought_insurance  affordability
0   22                 0              1
1   25                 0              0
2   47                 1              1
3   52                 0              0
4   46                 1              1

In [3]:
x = df.drop(['bought_insurance'] ,axis ='columns')
x

age  affordability
0    22              1
1    25              0
2    47              1
3    52              0
4    46              1
5    56              1
6    55              0
7    60              0
8    62              1
9    61              1
10   18              1
11   28              1
12   27              1
13   29              0
14   49              1
15   55              0
16   25              0
17   58              1
18   19              1
19   18              0
20   21              1
21   26              0
22   40              0
23   45              1
24   50              0
25   54              1
26   23              1

In [4]:
from sklearn.model_selection import train_test_split
x_train ,x_test , y_train,  y_test = train_test_split( x ,df.bought_insurance , test_size =0.25)

In [5]:
x_train.shape

(20, 2)

In [6]:
y_train

25    1
7     1
6     0
15    1
16    1
10    0
4     1
22    1
0     0
26    0
24    1
5     1
20    0
18    0
3     0
12    0
9     1
2     1
8     1
21    0
Name: bought_insurance, dtype: int64

In [7]:
x_test.shape

(7, 2)

In [8]:
y_test.shape

(7,)

In [9]:
#data scaling
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age']/100
x_test_scaled = x_test.copy()
x_test_scaled['age'] = x_test_scaled['age']/100

In [10]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape =( 2 , ) , activation ='sigmoid' , kernel_initializer = 'one' , bias_initializer = 'zeros')
])

model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics=['accuracy']
              )
model.fit(x_train_scaled , y_train , epochs = 50)


Epoch 1/50
1/1 [==============================] - 1s 727ms/step - loss: 0.7650 - accuracy: 0.5500
Epoch 2/50
1/1 [==============================] - 0s 16ms/step - loss: 0.7646 - accuracy: 0.5500
Epoch 3/50
1/1 [==============================] - 0s 0s/step - loss: 0.7643 - accuracy: 0.5500
Epoch 4/50
1/1 [==============================] - 0s 0s/step - loss: 0.7639 - accuracy: 0.5500
Epoch 5/50
1/1 [==============================] - 0s 0s/step - loss: 0.7635 - accuracy: 0.5500
Epoch 6/50
1/1 [==============================] - 0s 0s/step - loss: 0.7632 - accuracy: 0.5500
Epoch 7/50
1/1 [==============================] - 0s 0s/step - loss: 0.7628 - accuracy: 0.5500
Epoch 8/50
1/1 [==============================] - 0s 0s/step - loss: 0.7624 - accuracy: 0.5500
Epoch 9/50
1/1 [==============================] - 0s 0s/step - loss: 0.7621 - accuracy: 0.5500
Epoch 10/50
1/1 [==============================] - 0s 0s/step - loss: 0.7617 - accuracy: 0.5500
Epoch 11/50
1/1 [===========================

In [11]:
model.predict([[.45 , 0]])

array([[0.5937444]], dtype=float32)

In [12]:
model.evaluate(x_test_scaled, y_test)

1/1 [==============================] - 0s 251ms/step - loss: 0.6388 - accuracy: 0.4286


[0.6387786865234375, 0.4285714328289032]

In [13]:
slop , intersept = model.get_weights()
slop[0]

array([0.9528802], dtype=float32)

In [14]:
intersept

array([-0.04932961], dtype=float32)

In [15]:
def log_loss(y_trueth, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted]
    y_predicted_new = np.array(y_predicted_new)
    loss = - np.mean(y_trueth*np.log(y_predicted_new) + (1-y_trueth)*np.log(1-y_predicted_new))
    return loss

In [16]:
def sigmoid(x):
    return (1/(1+np.exp(-x)))

In [17]:
def gradient_descent(age, affordability , y_trueth, epochs):
    w1=1
    w2=1
    bias=0
    n=len(age)
    rate=0.001
    for i in range(epochs):
        y=w1*age+ w2*affordability + bias
        y_predicted =sigmoid(y)
        loss = log_loss(y_trueth,y_predicted)
        w1d = (1/n)*np.dot(np.transpose(age), (y_predicted-y_trueth))
        w2d = (1/n)*np.dot(np.transpose(affordability), (y_predicted-y_trueth))
        dbias = (1/n)*(y_predicted-y_trueth)
        w1 = w1-rate*w1d 
        w2 = w2-rate*w2d
        bias = bias - rate*dbias
        print("w1:",w1,end=" ")
        print("w2:" ,w2, end=" ")
        print( "bias: ", bias )
        if(loss==0.6297):
            break;
    return w1 , w2 ,bias 
        

In [18]:
gradient_descent( x.age , x.affordability ,  df.bought_insurance,5 )

w1: 0.9865555555712591 w2: 0.9997407407410401 bias:  0    -3.703704e-05
1    -3.703704e-05
2     0.000000e+00
3    -3.703704e-05
4     0.000000e+00
5     0.000000e+00
6    -3.703704e-05
7     0.000000e+00
8     0.000000e+00
9     0.000000e+00
10   -3.703704e-05
11   -3.703704e-05
12   -3.703704e-05
13   -3.703704e-05
14    0.000000e+00
15    0.000000e+00
16    5.143704e-16
17    0.000000e+00
18   -3.703704e-05
19   -3.703704e-05
20   -3.703704e-05
21   -3.703704e-05
22    0.000000e+00
23    0.000000e+00
24    0.000000e+00
25    0.000000e+00
26   -3.703704e-05
dtype: float64
w1: 0.9731111111468695 w2: 0.9994814814821646 bias:  0    -7.407407e-05
1    -7.407407e-05
2     0.000000e+00
3    -7.407407e-05
4     0.000000e+00
5     0.000000e+00
6    -7.407407e-05
7     0.000000e+00
8     0.000000e+00
9     0.000000e+00
10   -7.407407e-05
11   -7.407407e-05
12   -7.407407e-05
13   -7.407407e-05
14    0.000000e+00
15    0.000000e+00
16    1.234223e-15
17    0.000000e+00
18   -7.407407e-05
19   

(0.9327777779136619,
 0.9987037037063181,
 0    -1.851852e-04
 1    -1.851852e-04
 2     0.000000e+00
 3    -1.851852e-04
 4     0.000000e+00
 5     0.000000e+00
 6    -1.851852e-04
 7     0.000000e+00
 8     0.000000e+00
 9     0.000000e+00
 10   -1.851852e-04
 11   -1.851852e-04
 12   -1.851852e-04
 13   -1.851852e-04
 14    0.000000e+00
 15    0.000000e+00
 16    5.624702e-15
 17    0.000000e+00
 18   -1.851852e-04
 19   -1.851852e-04
 20   -1.851852e-04
 21   -1.851852e-04
 22    0.000000e+00
 23    0.000000e+00
 24    0.000000e+00
 25    0.000000e+00
 26   -1.851852e-04
 dtype: float64)

In [19]:
def batch_gradient_descent(x,y_true,epochs,learning_rate=0.01):
    number_of_feature=x.shape[1]